<?php

const DEPORTISTA = "DEPORTISTA";

const DEP_ID = "DEP_ID";
const DEP_NOMBRE = "DEP_NOMBRE";
const DEP_DEPORTE = "DEP_DEPORTE";
const DEP_EQUIPO = "DEP_EQUIPO";

const DEP_MODIFICACION = "DEP_MODIFICACION";
const DEP_ELIMINADO = "DEP_ELIMINADO";
